version: '3.7'

services:
  backend:
    build: ./app
    restart: always
    command: uvicorn app.main:app --reload --port 8000 --host 0.0.0.0 --proxy-headers
    volumes:
      - ./app/:/ascenda/app
    ports:
      - "8000:8000"
      - "5678:5678"
    env_file:
      - app/.env

  db:
    image: mongo
    restart: always
    volumes:
      - ./database:/data/db
    command: --quiet
    ports: 
      - 27018:27017

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - backend